### PR TITLE
Version reference fixed to 1.9.5

### PR DESCRIPTION
**Pull request by EricMarcil**
Fixed version reference that was forgotten in the PR #412

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
I realise FS100 and DX100 don't show these versions anywhere, but it would be good to include the complete set of updated binaries in this PR.

That'll make it that much easier to reason about what changed in the future, and easier to match binaries to Git hashes.

**Comment by EricMarcil** [comment]
Yes, I saw that the FS100 and DX100 binary were not included but I actually compiled them.  GitHub won't pick them up because the resulting compiled binary doesn't actually change.

**Comment by gavanderhoorn** [comment]
> GitHub won't pick them up because the resulting compiled binary doesn't actually change.

Ok, thanks for confirming that.

**Review by gavanderhoorn — APPROVED** [review]
I can't test this on real hw, but this rectifies #412 and is the same pattern used in earlier PRs which update MotoROS version numbers.

**Comment by gavanderhoorn** [comment]
Unfortunately this will mean you'll have to update the wiki again @EricMarcil. At least for the affected binaries.

**Comment by EricMarcil** [comment]
@gavanderhoorn I expected that.  It's done and I've confirmed that the downloaded .out was matching the MD5 hash.
Thanks for the quick turn around.

**Pull request merged**
