### PR TITLE
Fixes ros-industrial/motoman#260: fix warnings with -Wall

### PR DESCRIPTION
**Pull request by dambrosio**
Changed for loop index variables to use size_t when comparing with vector size and corresponding ROS console output format string to %lu, JointFeedbackExRelayHandler create_messages now has return value

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
As in my comment to #262: could I ask you to please use separate commits for formatting changes / code changes and other changes? Especially the "JointFeedbackExRelayHandler create_messages now has return value" bit should absolutely be in a separate commit.

**Comment by dambrosio** [comment]
> As in my comment to #262: could I ask you to please use separate commits for formatting changes / code changes and other changes? Especially the "JointFeedbackExRelayHandler create_messages now has return value" bit should absolutely be in a separate commit.

Separated into multiple commits. Let me know if this is what you had in mind.

**Comment by gavanderhoorn** [comment]
Closing.

Rebased version in #388.

**Comment by gavanderhoorn** [comment]
Thanks @dambrosio for your initial PR.

And apologies for merging it so late of course, that was not the intention.

**Pull request closed without merging**
