### PR TITLE
MotoROS v1.7.2

### PR DESCRIPTION
**Pull request by ted-miller**
- Add velocity feedback for DX100 and FS100 controllers.

### CODE REVIEW

**Review by gavanderhoorn — APPROVED** [review]
This seems to work well in a quick test. Haven't noticed any regressions.

Velocity data coming out of this is a bit noisy, and there appears to be some lag, but it does not look as discretised as the previous implemention.

**Comment by gavanderhoorn** [comment]
I'll wait on Travis before merging this.

**Comment by gavanderhoorn** [comment]
Thanks for adding this @ted-miller.

@mbharatheesha fyi.

**Comment by gavanderhoorn** [comment]
I'm slightly confused about the commits included in this PR, but a squash merge will probably 'fix' that.

**Comment by gavanderhoorn** [comment]
Thanks @ted-miller :+1:

**Comment by Danfoa** [comment]
Hi @ted-miller @gavenderhoorn, first thanks for offering this support. I just want to mention that with this update, the troubleshooting web page of the motoman package needs to be updated, since it mentions that velocity feedback is not present in the FS100 controller.

**Pull request merged**
