### PR TITLE
MotoROS: Improve clearing of internal motion queue during error states

### PR DESCRIPTION
**Pull request by ted-miller**
Note that this does not actually resolve any current user issues. It was discovered while investigating a different issue that is not caused by MotoROS.

### CODE REVIEW

**Review by gavanderhoorn — DISMISSED** [review]
Haven't run this on our YRC1000, but the proposed changes look OK.

**Comment by gavanderhoorn** [comment]
Have you tested this on HW @ted-miller ?

**Comment by ted-miller** [comment]
Yes

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Thanks @ted-miller.

Would you update the wiki?

**Pull request merged**
