### PR TITLE
Fix for issue #159: add missing dependency on std_srvs

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

No functional changes.

Let's see what Travis thinks.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
00b898c and 1dc51b3 are extra and just make `catkin_lint` happier.

**Comment by shaun-edwards** [comment]
Looks like Travis couldn't find the branch...perhaps just a hiccup.  Restarted.

**Comment by shaun-edwards** [comment]
@gavanderhoorn, this is some unbelievable bad luck.  We make a fix, Travis passes, but the build farm fails....all before a sync.  The PR, which fixes the issue, now fails on Travis in a way that I have never seen before.  Do you have any insight into why Travis is failing on just the push?  Perhaps its something `industrial_ci` did?

**Comment by gavanderhoorn** [comment]
> Do you have any insight into why Travis is failing on just the push? Perhaps its something `industrial_ci` did?

yes: I should not have -- by accident -- pushed the same branch to both my personal fork *and* the main repository. Travis somehow linked the duplicated branch (on `motoman`) to this PR, I deleted the branch when I discovered my mistake, but Travis was still trying to build it.

The `travis-ci/pr` build passed, so that is the important one.

I've just pushed the duplicated branch to `motoman` again so we can let Travis complete its build. Afterwards we'll only merge the one in the PR.

That should fix / work-around this.

**Comment by shaun-edwards** [comment]
That explains...no big deal.  Thanks for reacting so quickly.  I would have missed the item on Discourse.

**Review by shaun-edwards — APPROVED** [review]
LGTM

**Comment by shaun-edwards** [comment]
I'll merge and then do the release tonight.

**Comment by gavanderhoorn** [comment]
This will need to be syned with `indigo-devel` as well ..

**Pull request merged**
