### PR TITLE
Set of mostly cosmetic changes to MotoROS sources (typos & whitespace)

### PR DESCRIPTION
**Pull request by gavanderhoorn**
Discussed via email.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@ted-miller: I haven't rebased on the state of `indigo-devel` in #114, as your `indigo-devel` is a bit behind `HEAD` in this repository. Merging should be possible in any case.

**Comment by gavanderhoorn** [comment]
@ted-miller: could you give your stamp of approval here?

**Comment by ted-miller** [comment]
:+1:
I approve.

**Comment by gavanderhoorn** [comment]
@shaun-edwards: I'll leave actually merging this to you.

**Comment by shaun-edwards** [comment]
@gavanderhoorn, it looks like approving some prior PRs is now causing this one to have conflicts.  I'd also like to suggest this change be pushed into `jade-devel`, unless you have a reason for it to go into `indigo`?  (if you agree, wait for me to sync `jade-devel` before issuing the new PR).

**Comment by gavanderhoorn** [comment]
I'll fix the merge conflicts.

As to these changes going into `indigo-devel` or `jade-devel`: if possible, could we get this into Indigo? It's all whitespace, comments and / or other cosmetic changes.

Afaik, @ted-miller has compile-tested this as well.

See also my https://github.com/ros-industrial/motoman/pull/121#issuecomment-243055794 in #121.

**Comment by gavanderhoorn** [comment]
@shaun-edwards: rebased.

**Comment by ted-miller** [comment]
I have compile tested.  But, I just realized that your commits don't have the binaries for your updates.  (At least not with the "official" compiler).  Plus, I have some other minor updates.

For the life of me, I can't figure out how to sync @gavanderhoorn 's latest commits onto my fork so that I can directly upload to this PR.  I'm using Github for Windows which has a truly terrible UI.  So... I'm going to email the files (apparently I can't attach a zip to this conversation).  Can you please merge/commit these?

Changes:
Add new ParameterTypes.h to the visual studio project.
Update version number in Controller.h.
New binaries.

**Comment by gavanderhoorn** [comment]
@ted-miller: I've added the commits you sent me.

> Plus, I have some other minor updates.

Running a diff on the changed files I don't see anything besides the updated version nr. Have I missed something?

**Comment by gavanderhoorn** [comment]
@ted-miller wrote:

> For the life of me, I can't figure out how to sync @gavanderhoorn 's latest commits onto my fork so that I can directly upload to this PR. I'm using Github for Windows which has a truly terrible UI.

I'm not sure how that would work with Github for Windows, but there are a few ways. All of which would involve `git` on the command line though (which is available in Github for Windows). Let me know if you'd like me to explain.

> (apparently I can't attach a zip to this conversation)

Hm, that should actually be possible? have you tried dragging-and-dropping the zip _onto_ the textbox you write your comment in?

**Comment by ted-miller** [comment]
I updated the version number in Controller.h and added ParameterTypes.h to the vcxproj.  (That's it)

I tried dropping on the textbox.  It just rejected the file, even though it said .zip was a valid extension.  Maybe it opened the zip and rejected one of the files inside it???

**Comment by gavanderhoorn** [comment]
> I updated the version number in Controller.h and added ParameterTypes.h to the vcxproj. (That's it)

ok, good. Just making sure.

> I tried dropping on the textbox. It just rejected the file, even though it said .zip was a valid extension. Maybe it opened the zip and rejected one of the files inside it???

hm, that should've worked. Anyway, I've added the changes to this PR.

**Comment by shaun-edwards** [comment]
+1...thanks for the contribution....merging.

**Pull request merged**
