### PR TITLE
Add ma2010, motopos d500 support and ma2010 moveit_config

### PR DESCRIPTION
**Pull request by tdl-ua**
Added support packages for both MA2010 manipulator and D500 positioner, and a movit_config package for the MA2010 manipulator. 

Motopos D500 support package is called `motoman_motopos_d500_support`. Is this correct or should it be renamed to `motopos_d500_support`? Am assuming that only manipulators are called "motoman".

Testing:
* both ma2010 and d500 support packages have been tested with `test_[robot/positioner model].launch`: all joints move as intended
* `motoman_ma2010_moveit_config`: 
  * `moveit_planning_execution.launch sim:=true`: planning and execution
  working
  * `moveit_planning_execution.launch` has not been tested on a physical robot

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@tdl-ua: thanks for the PR.

Could I be difficult and ask you to split the single commit you have now into three? One for the MA2010 support pkg, one for the D500 support package and finally one for the MA2010 MoveIt configuration?

You could either create a new PR, or force-push to the same branch as you've used for this PR. The PR will update automatically.

**Comment by tdl-ua** [comment]
@gavanderhoorn No problem, I can make that happen with the force-pushing method.

**Comment by tdl-ua** [comment]
@gavanderhoorn I'll force-push one more time after cleaning up the commits (incorporate https://github.com/ros-industrial/motoman/pull/266/commits/df24c01475061fc65e612a65af95d840f34aa789 into https://github.com/ros-industrial/motoman/pull/266/commits/26dc3e1c935b47afc229a9f0cfdfa0c8dc661a81). 

Other than that, I've been using the packages in this PR for quite a while now on our system without running into major issues.

**Comment by gavanderhoorn** [comment]
> @gavanderhoorn I'll force-push one more time after cleaning up the commits (incorporate [df24c01](https://github.com/ros-industrial/motoman/commit/df24c01475061fc65e612a65af95d840f34aa789) into [26dc3e1](https://github.com/ros-industrial/motoman/commit/26dc3e1c935b47afc229a9f0cfdfa0c8dc661a81)).
> 
> Other than that, I've been using the packages in this PR for quite a while now on our system without running into major issues.

Thanks @tdl-ua.

Our robot was out-of-commission for quite some time, which caused me to have to deprioritise reviewing these PRs. I'm slowly getting back to this again (as everything is in working order again).

We're making some changes to the maintenance of this repository, so I'm confident we can avoid such delays in the future.

**Comment by tdl-ua** [comment]
@gavanderhoorn Commit clean-up is done. 

Have also tested everything again on our system and everything moves as it should.

PR is also up to date with `kinetic-devel`.

**Comment by gavanderhoorn** [comment]
Rebased version in #391.

Thanks for the initial PR @tdl-ua :+1: 

And apologies for merging late.

**Pull request closed without merging**
