### PR TITLE
Fixes ros-industrial/motoman#262 : roslint cpp passes

### PR DESCRIPTION
**Pull request by dambrosio**
added config in MotoPlus to ignore header files, updated copyrights to use cpp style comments, package roslint now is part of catkin_run_tests

Note: A leading line was added on all copyright headers as lint randomly errors about "At least two spaces is best between code and comments  [whitespace/comments] [2]".

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks for this PR -- and the other ones.

Before I review however: could I ask you to split changes into multiple commits? Right now actual content changes (to source files/headers) and changes to packaging and linting setups are mixed, which makes reverting changes to some of these files more involved than need be.

I realise this may be inconvenient, but it's easier to review and nicer to maintain.

---

Edit: please leave the `MotoPlus` directory completely out of the linting setup. It's not code that gets compiled on the ROS/PC side and due to how MotoPlus is integrated into Visual Studio (on Windows) has some specific requirements / conventions to formatting and code layout/structure.

**Comment by dambrosio** [comment]
> Thanks for this PR -- and the other ones.
> 
> Before I review however: could I ask you to split changes into multiple commits? Right now actual content changes (to source files/headers) and changes to packaging and linting setups are mixed, which makes reverting changes to some of these files more involved than need be.
> 
> I realise this may be inconvenient, but it's easier to review and nicer to maintain.
> 
> Edit: please leave the `MotoPlus` directory completely out of the linting setup. It's not code that gets compiled on the ROS/PC side and due to how MotoPlus is integrated into Visual Studio (on Windows) has some specific requirements / conventions to formatting and code layout/structure.

No problem on splitting into multiple commits and ignoring the MotoPlus directory from lint. What would be the best way do this, create a new branch with the separated commits and a new PR that references this? Or should I just create a new PR and delete this one? 
Thanks

**Comment by gavanderhoorn** [comment]
After fixing your local state, you can just force push everything to the branch you've used already. The PR will update automatically.

**Review by dambrosio — COMMENTED** [review]
FYI, a few files contained hidden windows characters that caused issues with the ros linter, I ran `dos2unix` to remove these hidden characters which in turn caused the diff to show the entire file change.

**Comment by gavanderhoorn** [comment]
> FYI, a few files contained hidden windows characters that caused issues with the ros linter, I ran `dos2unix` to remove these hidden characters which in turn caused the diff to show the entire file change.

Those "hidden characters" are most likely UTF-8 [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) characters. Those are inserted by editors that are UTF-8 aware, Visual Studio being one of them.

As Yaskawa is (partly) a Japanese company, and some of its employees are contributing to this repository, those characters have been introduced there to make sure that locales/languages other than English will be correctly represented / recognised by the various editors.

Could I ask you to please revert the commit(s) where you remove those markers?

**Comment by gavanderhoorn** [comment]
@dambrosio:

> Edit: please leave the `MotoPlus` directory completely out of the linting setup. It's not code that gets compiled on the ROS/PC side and due to how MotoPlus is integrated into Visual Studio (on Windows) has some specific requirements / conventions to formatting and code layout/structure.

did you ignore the `MotoPlus` directory completely? I see the [CPPLINT.cfg](https://github.com/ros-industrial/motoman/pull/263/files#diff-f3f0d054f0b9db8b131fa4b8a840110f) which ignore `.h` files there, but all files in that directory should be ignored -- for now.

**Comment by dambrosio** [comment]
> @dambrosio:
> 
> > Edit: please leave the `MotoPlus` directory completely out of the linting setup. It's not code that gets compiled on the ROS/PC side and due to how MotoPlus is integrated into Visual Studio (on Windows) has some specific requirements / conventions to formatting and code layout/structure.
> 
> did you ignore the `MotoPlus` directory completely? I see the [CPPLINT.cfg](https://github.com/ros-industrial/motoman/pull/263/files#diff-f3f0d054f0b9db8b131fa4b8a840110f) which ignore `.h` files there, but all files in that directory should be ignored -- for now.

To my understanding roslint only checks **.h** and **.cpp** files. Since the other files in that directory are **.c**, I did not include in the **CPPLINT.cfg** file.

**Comment by gavanderhoorn** [comment]
> To my understanding roslint only checks **.h** and **.cpp** files. Since the other files in that directory are **.c**, I did not include in the **CPPLINT.cfg** file.

you're right. It does only check `.cpp` files.

**Comment by dambrosio** [comment]
> > FYI, a few files contained hidden windows characters that caused issues with the ros linter, I ran `dos2unix` to remove these hidden characters which in turn caused the diff to show the entire file change.
> 
> Those "hidden characters" are most likely UTF-8 [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) characters. Those are inserted by editors that are UTF-8 aware, Visual Studio being one of them.
> 
> As Yaskawa is (partly) a Japanese company, and some of its employees are contributing to this repository, those characters have been introduced there to make sure that locales/languages other than English will be correctly represented / recognised by the various editors.
> 
> Could I ask you to please revert the commit(s) where you remove those markers?

No problem on the revert. A few quick questions: 

1. If we are saying we need UTF-8 [BOM] shouldn't this be inserted in every file, instead of a few of them?
2. These UTF-8 windows characters do not play well with the roslint script in terms of C-style comments. If the UTF-8 characters are left we should change the comments to use C++-style comments, and a newline is required at the top of the file. Do you want this in every file or just the files that have the BOM?

**Comment by gavanderhoorn** [comment]
Closing.

Rebased version in #387.

**Comment by gavanderhoorn** [comment]
Thanks @dambrosio for your initial PR.

And apologies for merging it so late of course, that was not the intention.

**Pull request closed without merging**
