### PR TITLE
v1.3.8 - MotoROS Driver

### PR DESCRIPTION
**Pull request by ted-miller**
- Automatically scan robot-setup parameters and notify user if there is a configuration problem.
- Fix bug with receiving multiple SimpleMsg packets in a single Recv command.

### CODE REVIEW

**Comment by shaun-edwards** [comment]
Thanks @ted-miller.  I'll review later this afternoon.  I'll also merge these changes into the indigo branch, as this is the branch a lot of people use.

**Review by shaun-edwards — APPROVED** [review]

**Comment by shaun-edwards** [comment]
@ted-miller, this looks good.  I especially like the code that scans the configuration.  That should improve the user experience and reduce the number of question from users.  Great thinking!

**Comment by gavanderhoorn** [comment]
Yes, great thinking @ted-miller ;)

Thanks for implementing this 🍻 🎆

**Comment by ted-miller** [comment]
Yes, I did think great! Go me!
Good thing @gavanderhoorn didn't try to take credit for requesting this feature a month ago...

**Pull request merged**
