### PR TITLE
MotoRos v1.9.1 Fix for older controller

### PR DESCRIPTION
**Pull request by EricMarcil**
This fixes version 1.9.0 that was no longer working for older controller.  PFL related I/O signals (which are not available on older controllers) were put in condition compile statements.

### CODE REVIEW

**Comment by EricMarcil** [comment]
This should resolve issue #315

**Comment by gavanderhoorn** [comment]
Thanks for the PR @EricMarcil.

I'll have time early next week to test it on our YRC1000.

**Comment by gavanderhoorn** [comment]
@acbuynak @impet14 and @alexander-jh: could you confirm the version of MotoROS in this PR fixes the problems you were encountering?

**Comment by acbuynak** [comment]
Confirming that the proposed v1.9.1 fixed all errors identified in [Issue #315](https://github.com/ros-industrial/motoman/issues/315)

This was on a FS100, single robot system.

**Review by acbuynak — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Thanks for the confirmation @acbuynak.

I'd like to get a confirmation from someone with a YRC1000. Unfortunately my own robot is somewhat difficult to use right now.

**Comment by EricMarcil** [comment]
@gavanderhoorn I ran my tests on a YRC1000 and it worked fine.

**Comment by gavanderhoorn** [comment]
@EricMarcil: does that YRC1000 have multiple motion groups?

**Comment by EricMarcil** [comment]
No, just a single group.  I have a DX200 with an external axis back at the office but I'm not sure when I'll get a chance to go there next.

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Ok.

I'm going to go ahead and merge this PR.

We have one test from a user with an affected controller and one test from a non-affected controller and both report no regressions.

I won't have an opportunity to test this myself soon, and I don't want to keep distributing a broken version of MotoROS.

**Comment by gavanderhoorn** [comment]
@EricMarcil: will you also update the [wiki page](http://wiki.ros.org/motoman_driver/Tutorials/indigo/InstallServer) and make the links point to the correct binaries?

**Comment by gavanderhoorn** [comment]
Thanks @acbuynak for testing :+1:

**Comment by EricMarcil** [comment]
@ted-miller Can you update the binary on the wiki page.  Thanks

**Comment by ted-miller** [comment]
Done

**Comment by gavanderhoorn** [comment]
Diff: [here](http://wiki.ros.org/action/diff/motoman_driver/Tutorials/indigo/InstallServer?action=diff&rev1=50&rev2=51).

**Pull request merged**
