### PR TITLE
Cast vector.size() to int to eliminate nasty compile warnings

### PR DESCRIPTION
**Pull request by pbeeson**
I got tired of seeing 15 lines of compiler warnings about ros logging not getting the right type, so I decided to make this tiny fix.

### CODE REVIEW

**Comment by shaun-edwards** [comment]
Thanks @pbeeson for the contribution.  I re-kicked off the travis builds.  I'm going to be out next week, so it might take me until next week to merge.

**Comment by pbeeson** [comment]
I merged a minor, but needed fix into my master without thinking of this outstanding pull request.  It should be harmless.

**Comment by shaun-edwards** [comment]
No problem.  I plan to work through these soon, but I'm giving some other repos my attention.  I assume you aren't waiting on these.  Thanks for the contribution.

**Comment by shaun-edwards** [comment]
+1...Thanks @pbeeson for the contribution.

**Pull request merged**
