### PR TITLE
MH50 meshes update

### PR DESCRIPTION
**Pull request by EricMarcil**
This is correcting small errors in the original MH50 meshes that were reported in issue #276
- .stl files were updated for both visual and collision

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@EricMarcil: did you close this on purpose?

I do not see any related changes in [the history for this package](https://github.com/ros-industrial/motoman/commits/kinetic-devel/motoman_mh50_support).

**Comment by EricMarcil** [comment]
Yes, looks like a mistake because I'm saying that I'm waiting a the change review on #276.  
There is a forced-pushed on Mar 6 but I guess that is not a merge.

**Comment by gavanderhoorn** [comment]
What could have happened is that you accidentally pushed an "empty changeset", which tends to close PRs on Github. That would be what the force-push could've done.

I'll recover the commits tomorrow and submit them as a new PR (with provenance retained).

**Comment by gavanderhoorn** [comment]
As I could not recover this PR, I've submitted a replacement: #357.

**Pull request closed without merging**
