### PR TITLE
MH50 meshes corrections

### PR DESCRIPTION
**Pull request by EricMarcil**
MH50 mesh correction in relation to issue #276 "tool0 frame not at end of link_6_t in motoman_mh50_support"

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@EricMarcil: are you using Windows or Linux?

**Comment by EricMarcil** [comment]
@gavanderhoorn: Windows.  I have GitHub Desktop installed.

**Comment by gavanderhoorn** [comment]
Ok. If you open a git shell (should be possible from some drop down menu), does it use a regular Windows cmd prompt (ie: `cmd.exe`), Powershell or Bash?

**Comment by EricMarcil** [comment]
I have both Git CMD and Git Bash.

**Comment by gavanderhoorn** [comment]
Open a bash shell, `cd` to the directory containing your local clone of `motoman` and then run `git remote -v`.

If it doesn't show `origin https://github.com/ros-industrial/motoman.git` (for instance it only shows: `origin https://github.com/EricMarcil/motoman.git`) then do this:

```
git remote add upstream https://github.com/ros-industrial/motoman.git
```

if you do have `origin` set to `https://github.com/ros-industrial/motoman.git` then you're set.

**Comment by EricMarcil** [comment]
This is what I get, which I believe is correct.

```bash
$ git remote -v
origin  https://github.com/EricMarcil/motoman.git (fetch)
origin  https://github.com/EricMarcil/motoman.git (push)
upstream        https://github.com/ros-industrial/motoman.git (fetch)
upstream        https://github.com/ros-industrial/motoman.git (push)
```

**Comment by gavanderhoorn** [comment]
Great.

Now do (in the same shell):

```
git fetch upstream
git checkout -b issue276 upstream/kinetic-devel
git cherry-pick ce5068a
git push origin issue276
```

With the `cherry-pick` we add just the commit that fixes the mesh to your new branch.

Make sure all commands return successfully (ie: no errors or warnings).

Then, to fix your local clone (sync it with `upstream`):

```
git checkout kinetic-devel
git fetch upstream
git reset --hard upstream/kinetic-devel
git push origin kinetic-devel --force
```

`git` should say something about "forced update" after this (or something similar).

**Comment by EricMarcil** [comment]
Done!  Everything looks good and I've check that the main branch now has the changes.
Thanks!

**Comment by gavanderhoorn** [comment]
The only thing you now need to do is to open a new PR from https://github.com/ros-industrial/motoman/compare/kinetic-devel...EricMarcil:issue276.

**Comment by EricMarcil** [comment]
OK, It's reopened.
So we are good for now and wait for it to be reviewed...

**Pull request closed without merging**
