### PR TITLE
Fix StopMotion delayed reaction when queue is full

### PR DESCRIPTION
**Pull request by EricMarcil**
Added condition to stop AddPulseIncPointToQ loop when StopMotion is requested.

### CODE REVIEW

**Comment by riv-rbush** [comment]
Tested this on our [local branch](https://github.com/additiveautomations/motoman/commits/point-streamer-hotfix). It fixed issue #425.

**Comment by ted-miller** [comment]
@EricMarcil : wouldn't it make more sense to put `controller->bStopMotion` inside of `Ros_Controller_IsMotionReady`? This way the flag gets checked in other locations that look for motion-ready.

**Comment by ted-miller** [comment]
We need to figure something out for version numbering. Using the current scheme, we've only got one more update before v2.0.0. I think this would be confusing since all of the ROS 2 stuff seems to be named with a 2. 

Just something to think about moving forward. Maybe we just use more than one digit, like 1.9.11.

**Comment by gavanderhoorn** [comment]
After `9` comes `10`, not `0`. So we have plenty of minor nrs to go.

**Comment by EricMarcil** [comment]
@ted-miller Yes, it does make more sense.  I've made the changes.  If you could review it again.

@robertjbush If you have a chance, please grab the new binary and update your driver.  Let us know that the issue is still fixed with this new version.

**Review by ted-miller — APPROVED** [review]

**Comment by riv-rbush** [comment]
@EricMarcil I will test your latest changes this week.

**Comment by gavanderhoorn** [comment]
@robertjbush: have you had a chance to test this?

**Comment by riv-rbush** [comment]
@EricMarcil @gavanderhoorn Tested this on our Yaskawa Motoman GP8 with the commit 2f46450 and 19f459d cherry picked to our local branch. Test was a success, no error messages appeared on the console.

**Comment by gavanderhoorn** [comment]
thanks for reporting.

PS: the changes are on the MotoROS side, so I'm not exactly sure why you cherry-picked those commits (unless you are building your own MotoROS binaries).

**Comment by EricMarcil** [comment]
@robertjbush Thanks for the final check. 
I've squashed and merged the changes.  I'll update the binary on the wiki shortly.

**Pull request merged**
