### PR TITLE
Add ar2010 support

### PR DESCRIPTION
**Pull request by Doomerdinger**
Added support for the AR2010.

Requires #378.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Similar to #395, it appears this model has been constructed such that all `joint`s rotate around the Z axis.

Please see my https://github.com/ros-industrial/motoman/pull/395#issuecomment-841681941 there.

The `_macro.xacro` also contains some `gazebo` references, but doesn't include `inertial` nor `dynamics` elements. Which would make it not work with Gazebo in its current state afaik.

Could you please remove the Gazebo-isms?

As in #395: I'm willing to do it, but I wanted to ask you first.

**Comment by Doomerdinger** [comment]
@gavanderhoorn if you have time, you mentioned you could do what is necessary to bring this up to snuff to get it into the main branch?

I've had slim to no time to work on this stuff in quite some time.

**Comment by gavanderhoorn** [comment]
I'll try to get to it. Thanks for letting us know @Doomerdinger.

**Comment by gavanderhoorn** [comment]
Replacement: #480.

Thanks for the initial work @Doomerdinger :+1:

**Pull request closed without merging**
