### PR TITLE
Add HC10 support package

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

This PR adds just the HC10 support from #284.

A few fixups are included, as well as Collada meshes with proper colours (well, better) for all links.

hc10_before_after

We'll squash-merge this into `kinetic-devel`, to avoid the original `visual/*.stl`s from getting into the history.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Also note the use of `radians()` to convert joint limits in degrees to radians in-line ([here](https://github.com/ros-industrial/motoman/pull/298/files#diff-9b6e53a9a96d7f89a130c0a6d7bedb67R111) for instance).

**Comment by ted-miller** [comment]
I'm going to defer to @EricMarcil for the review. He's the one who generated the original support package for this.

**Comment by gavanderhoorn** [comment]
Note that I've had to approximate "Yaskawa white", as I couldn't find the actual RAL colour (in a quick Google).

The blue is RAL 5005 (or RViz's approximation of that).

**Comment by ted-miller** [comment]
> Note that I've had to approximate "Yaskawa white", as I couldn't find the actual RAL colour (in a quick Google). The blue is RAL 5005 (or RViz's approximation of that).

Official Yaskawa Blue is "**Pantone 2935 C**". 
image

I don't know the official "white" value.

**Comment by gavanderhoorn** [comment]
> Official Yaskawa Blue is "**Pantone 2935 C**".

Hm, interesting.

[This pdf](https://www.yaskawa.eu.com/fileadmin/Products/Accessories/Robotersockel/Flyer/Flyer_Equipment_RobotPedestals_BasePlates_E_08.2016-2.pdf) states that the XS pedestal series is:

>  Steel structure, painted, RAL 5005 (blue)

took that to mean: same as our robots (as that would seem to make sense).

---

According [to this](http://colormaid.spektran.com/pantone/2935-c), RAL 5005 is a similar colour (but definitely not the same).

Seeing as RViz isn't rendering it correctly anyway, I'll keep the colour I have now for the caps.

But good to know the name of the official colour.

**Comment by ted-miller** [comment]
My info is from our marketing department. It's very possible that the equipment color is slightly different than the logos and brochures. I'll check with our guys in the repair department; they should have some paint.

Either way, you've made a good-faith approximation. I wouldn't worry too much.

**Comment by gavanderhoorn** [comment]
Just merged #284. After @EricMarcil reviews this we can merge the support package.

**Comment by EricMarcil** [comment]
Sorry, it will probably go to tomorrow morning if you want me to do a pull on it and actually review it properly.  I'm trying to finish off the GP25 model for a customer.  I'll also be able to do a PR for that tomorrow.

**Comment by gavanderhoorn** [comment]
> Sorry, it will probably go to tomorrow morning if you want me to do a pull on it and actually review it properly.

I'll leave it up to you to decide whether that is necessary, but it would probably be a good idea.

Merging tomorrow is not problematic for me.

**Comment by ted-miller** [comment]
Blue for HC-10 is the Pantone 2935 C.
White is "Munsell N 9.5". (Anything in the category of "snow white" is close enough.)

**Review by EricMarcil — APPROVED** [review]
Everything looks good to me.
Thanks

**Comment by gavanderhoorn** [comment]
Thanks for the review.

(I'm actually sitting right next to an HC10 right now, pressing the *merge* button ;) )

**Pull request merged**
