### PR TITLE
Fixed warnings from xacro parser

### PR DESCRIPTION
**Pull request by progtologist**
Changed xacro files and launch files to remove the following warnings:
```
xacro.py is deprecated; please use xacro instead
```
```
xacro: Traditional processing is deprecated. Switch to --inorder processing!
```
```
redefining global property: pi
when processing file: motoman/motoman_sia5d_support/urdf/sia5d.xacro
```
```
deprecated: xacro tags should be prepended with 'xacro' xml namespace.
when processing file: motoman/motoman_sia5d_support/urdf/sia5d.xacro
```

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks for the PR :+1: 

I notice that the commit is not attributed to your account, as the email address used does not appear to be registered for it. Is that something you'd like to fix first?

**Comment by progtologist** [comment]
Thanks for pointing that out, I fixed it :)

**Review by gavanderhoorn — APPROVED** [review]
Nice fixes.

Thanks for submitting a PR.

**Comment by gavanderhoorn** [comment]
To avoid all the merge commits, I'm planning on squashing this.

<del>@progtologist: I believe that will make me the committer, but your 'unaffiliated' email the author. That would mean the commit would not be attributed to your account again.</del>

<del>If you'd like to fix that, you would have to update the author of the 95ac9fa and then do a force push.</del>

No, that's probably not the case. @progtologist is already listed as the author.

I'll wait on Travis and then do a squash merge.

**Comment by gavanderhoorn** [comment]
All ok, thanks again.

**Pull request merged**
