### PR TITLE
driver: remove deprecated 'robot_interface.launch' file

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Deprecated since Aug-2013.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Ping?

**Comment by shaun-edwards** [comment]
@gavanderhoorn, thanks for the contribution(s).  I'm working through things today, but it might be next week before I get to the last few PRs.

**Comment by gavanderhoorn** [comment]
No problem.

Any reason you haven't merged this one? It's essentially a simple `rm robot_interface.launch` change.

**Comment by shaun-edwards** [comment]
I opened #98 in the hopes of fixing Travis before I did any more merging.

**Comment by shaun-edwards** [comment]
+1...thanks for the contribution...merging.

**Pull request merged**
