### PR TITLE
adding another case for Motion Reply sub codes

### PR DESCRIPTION
**Pull request by sachinchitta**

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@sachinchitta, can you give some background on this change?  What is Skillsend and how do you expect to use it?  It's a small/minor change, so I'm just wondering if you intend to submit further PRs to support more functionality.

**Comment by sachinchitta** [comment]
This is just a match for the error code that seems to come out of MotoROS - 5010. It was labeled as unknown in the ROS driver but seems to correspond to SkillSend on the MotoPlus side.

**Comment by sachinchitta** [comment]
MotoPlus has these 11 subcodes for NOT READY: 
ROS_RESULT_NOT_READY_UNSPECIFIED = 5000,
    ROS_RESULT_NOT_READY_ALARM,
    ROS_RESULT_NOT_READY_ERROR,
    ROS_RESULT_NOT_READY_ESTOP,
    ROS_RESULT_NOT_READY_NOT_PLAY,
    ROS_RESULT_NOT_READY_NOT_REMOTE,
    ROS_RESULT_NOT_READY_SERVO_OFF,
    ROS_RESULT_NOT_READY_HOLD,
    ROS_RESULT_NOT_READY_NOT_STARTED,
    ROS_RESULT_NOT_READY_WAITING_ROS,
    ROS_RESULT_NOT_READY_SKILLSEND

ROS driver only has 10:
UNSPECIFIED = 5000,
  ALARM,
  ERROR,
  ESTOP,
  NOT_PLAY,
  NOT_REMOTE,
  SERVO_OFF,
  HOLD,
  NOT_STARTED,
  WAITING_ROS

**Comment by shaun-edwards** [comment]
+1... @sachinchitta, thanks for the contribution.

**Pull request merged**
