### PR TITLE
Created motoman_mh5_moveit_config

### PR DESCRIPTION
**Pull request by nsnitish**
@shaun-edwards  ! Moveit Configuration file as a part of Issue #172.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@nsnitish: I'm not entirely sure what happened here. The PR includes a single commit with "0.3.7" as commit message. Was that intentional?

**Comment by nsnitish** [comment]
@gavanderhoorn ! That was a mistake. I will update the commit.

**Comment by gavanderhoorn** [comment]
No problem, just asking.

Also: unless you discussed this with @shaun-edwards and you decided otherwise, new packages typically go into the `motoman_experimental` repository. The fact that `motoman_mh5_support` is in this repository does not mean the moveit config needs to be there as well.

**Comment by shaun-edwards** [comment]
@gavanderhoorn, The URDF for the mh5 has been vetted, I'm not sure why we should wait for the MoveIt package.  We have an MH5 robot that we are actively using.  I feel this is a relatively safe contribution.

**Comment by gavanderhoorn** [comment]
@shaun-edwards wrote:
> @gavanderhoorn, The URDF for the mh5 has been vetted, I'm not sure why we should wait for the MoveIt package. 

Because we have a dev process, and this is a new package.

**Comment by gavanderhoorn** [comment]
Btw: now that there is an MH support package in `motoman_experimental`, should the MH5 xacro be migrated and this MoveIt config be based on that?

**Comment by shaun-edwards** [comment]
The process is to make sure it is vetted.  I think it is.  However, moving it to `motoman_experimental` and migrating to `motoman_mh_support` brings up a bigger issue that I hadn't considered.  We will basically block all `mh` robots until they are all vetted.  We will have lost the ability to migrate them one by one since the `motoman_mh_support` dependency would have to be migrated to `motoman`.  Thoughts?

**Comment by gavanderhoorn** [comment]
@shaun-edwards wrote:
> The process is to make sure it is vetted.

That is not all there is to the process. Placing this in experimental also allows us to make sure the package can get exposed to use-cases and environments that are different from those it has seen when it is/was used by the original author/contributor, without all the stability and bw-compatibility requirements that go with a package that has been merged into and distributed from a non-experimental repository. The fact that you use it with your robot and haven't encountered any issues with it is not really important.

> We will basically block all `mh` robots until they are all vetted.  We will have lost the ability to migrate them one by one since the `motoman_mh_support` dependency would have to be migrated to `motoman`.

I'm not sure I understand what you are saying here.

**Comment by shaun-edwards** [comment]
@nsnitish, please close this and re-open against `motoman_experimental`

@gavanderhoorn, the `motoman_mh_support` package, after @nsnitish opens the PR, will contain files for the `mh5` and the `mh180`.  If we wanted to migrate just the `mh5`, we couldn't.  We would have to migrate both the `mh5` and the `mh180` because we couldn't "split" the `motoman_mh_support` package.

**Comment by gavanderhoorn** [comment]
@shaun-edwards wrote:
> @gavanderhoorn, the `motoman_mh_support` package, after @nsnitish opens the PR, will contain files for the `mh5` and the `mh180`.  If we wanted to migrate just the `mh5`, we couldn't.  We would have to migrate both the `mh5` and the `mh180` because we couldn't "split" the `motoman_mh_support` package.

yes, that is an unfortunate consequence of the many-variants-in-a-single-pkg approach.

Thinking about it a bit I can only come up with creating two packages: `motoman_mh_support` and `motoman_mh_support_experimental` (or something similar) and then manually migrating (ie: moving) sets of files between those.

That is not very elegant though.

**Comment by gavanderhoorn** [comment]
@nsnitish: did you intend to copy the ` kinematics_base_test` package into your PR? df2b85a seems to add the package as well as your MH5 test.

**Pull request closed without merging**
