### PR TITLE
readme: added license badge

### PR DESCRIPTION
**Pull request by hsd-dev**
Related to https://github.com/ros-industrial/ros_industrial_issues/issues/57

### CODE REVIEW

**Review by gavanderhoorn — CHANGES_REQUESTED** [review]
`motoman_mh12_support` actually is Apache 2 licensed.

That badge would need to be included as well.

**Comment by hsd-dev** [comment]
Then we need to update the wiki as well: http://wiki.ros.org/motoman

**Comment by gavanderhoorn** [comment]
The metapackage page does not list all the licenses of all the packages, just the license of the metapackage.

The [motoman_mh12_support](http://wiki.ros.org/motoman_mh12_support?distro=kinetic) page doesn't exist.

**Review by gavanderhoorn — APPROVED** [review]

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Thanks @ipa-hsd :+1:

**Pull request merged**
