### PR TITLE
Syncing Indigo and Indigo devel branches

### PR DESCRIPTION
**Pull request by shaun-edwards**
Sync in preparation for release.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@shaun-edwards: is this blocked on something in particular?

**Comment by gavanderhoorn** [comment]
🛎 ?

**Comment by shaun-edwards** [comment]
Was waiting on the changes in PR #133.

**Comment by gavanderhoorn** [comment]
Are you planning on syncing `jade-devel` with `indigo-devel` as well?

**Pull request merged**
