### PR TITLE
MotoROS v1.7.3

### PR DESCRIPTION
**Pull request by ted-miller**
- Fix unit scaling for velocity feedback on DX100 and FS100.

### CODE REVIEW

**Comment by ted-miller** [comment]
@gavanderhoorn  This should fix #208

**Comment by ted-miller** [comment]
@Tom-Pfahler Please make sure to pull this into your fork and recompile before posting your updates.

**Comment by gavanderhoorn** [comment]
@ted-miller: not sure what is going on here with the commits. I would've expected to see only 07fd8c3?

**Comment by ted-miller** [comment]
I have no idea why, but it says that I'm 9 commits ahead.  I also thought it was strange.  Maybe I just need to re-base?
9 commits ahead

**Comment by ted-miller** [comment]
Also, I'm thinking maybe we should kill this PR.  @Tom-Pfahler is going to submit a new one today for v1.8.0 that includes support for the YRC1000 Micro controller.

So, I'm thinking that I should just merge his changes locally and submit a new PR.  I think this would be easier for the revision history.  Your thoughts?

**Comment by gavanderhoorn** [comment]
Hm.

Well you could just hard reset your local `kinetic-devel` to `origin/kinetic-devel` (provided that `origin` points to `ros-industrial/kinetic-devel`).

You would lose your local changes (ie: 07fd8c3), but that is just a few lines (and you could even save those if you'd really want). Then first create a feature branch from`kinetic-devel` (fi: `motoros173`), re-apply the changes, push the feature branch and open a new PR.

Then after things get merged, do a `git fetch origin` (again: assuming it points to the main repository), and then a `git checkout kinetic-devel` (just to be sure) and finally a `git merge origin/kinetic-devel`. That should cleanly update your local `kinetic-devel` with the latest changes.

From that point on just avoid working in `kinetic-devel`, and your history should stay managable.

If things get really messy, you could always `git checkout kinetic-devel && git reset --hard origin/kinetic-devel` (note: you will lose local changes committed to `kinetic-devel`).

**Comment by gavanderhoorn** [comment]
If that sounds too complicated, we can always close this and have the fix for #208 as part of 1.8.0.

**Comment by gavanderhoorn** [comment]
Just tested this and 've verified that it works.

Would you want to submit a new PR @ted-miller?

**Comment by ted-miller** [comment]
Yeah. I'm going to submit a new one on Monday. There is another edit I need to make to the setup-validation library.

**Comment by ted-miller** [comment]
Closing. Will submit new PR with additional updates on top of these.

**Pull request closed without merging**
