### PR TITLE
Resubmit of 316: MH50 meshes update

### LINKED ISSUE #276: tool0 frame not at end of link_6_t in motoman_mh50_support
Hello,

this is issue regarding my question on ROS answers regarding motoman_mh50_support package.

> https://answers.ros.org/question/324031/motoman_mh50_support-urdf-frame-location/?comment=324060#post-id-324060

why is there some gap? it should be exactly at the end, or?

Thanks.

---

Edit (by @gavanderhoorn): including the screenshot @npd26 included in his ROS Answers post here (to avoid it going missing):

Screenshot-from-2019-05-26-15-47-21

### PR DESCRIPTION
**Pull request by gavanderhoorn**
This is #316, as that never got merged.

It's the exact same commit by @EricMarcil, but now in a new branch and committed today (but authored on the original date).

This should fix #276.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@EricMarcil: could you clarify why you changed *all* meshes, instead of only for `T`?

#276 reports a problem with the toolframe, but this PR changes all meshes.

**Comment by gavanderhoorn** [comment]
@EricMarcil: as I submitted this PR myself, you'll need to review it before we can merge this.

**Review by EricMarcil — APPROVED** [review]

**Comment by EricMarcil** [comment]
@gavanderhoorn I've reviewed and approved the commit.  Thanks for fixing it.

**Comment by EricMarcil** [comment]
> @EricMarcil: could you clarify why you changed all meshes, instead of only for T?
> #276 reports a problem with the toolframe, but this PR changes all meshes.

The original model was not generated at the robot home position.  I had manually realigned the models as best as I could but there were probably still small errors (< 1 mm) on other links.  So I thought it best so regenerate everything one I got a proper model.

**Comment by gavanderhoorn** [comment]
Thanks for the review and the initial fix @EricMarcil :+1: 

> So I thought it best so regenerate everything one I got a proper model.

agreed.

**Pull request merged**
