### PR TITLE
MH50 meshes corrections

### PR DESCRIPTION
**Pull request by EricMarcil**
Correction of the MH50 meshes in relation to issue ros-industrial#276 "tool0 frame not at end of link_6_t in motoman_mh50_support"

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@EricMarcil: quick question: if you only fixed `link_t`, why does the PR show all meshes have changed?

**Comment by EricMarcil** [comment]
Actually the error was with the L-axis and then propagated all the way to the T-axis.
So yes, the Base and S-axis could have stayed the same but the other models had to be changed.  I didn't really think about it at the time and just redid everything.

**Review by gavanderhoorn — CHANGES_REQUESTED** [review]
Apologies for taking so long.

I've *requested changes* as it seems the origin of `link_6_t` is not in the centre of the disk:

rviz_screenshot_2019_08_28-17_14_42

This is after rotating `joint_6_t`: notice how the last link is not covering `link_5_b` (the grey link, I've temporarily changed the colour).

**Comment by EricMarcil** [comment]
I've made correction and pushes under Issue #276.  Please review when you have a chance.  Thanks.

**Review by gavanderhoorn — DISMISSED** [review]

**Comment by gavanderhoorn** [comment]
@EricMarcil: unfortunately it would appear the T link is still not correctly centred.

The easiest way to check would be to load the 'test' launch file:

```
roslaunch motoman_mh50_support test_mh50.launch
```

zoom in on the flange and then rotate `joint_6_t`. You'll notice the disk of the flange has a slight 'wobble'.

Is the source mesh not centred either? Is this something you have to do manually?

**Comment by gavanderhoorn** [comment]
Replaced by #316.

**Pull request closed without merging**
