### PR TITLE
Fix alarm code in robot status

### PR DESCRIPTION
**Pull request by ted-miller**
If there is an alarm of any type other than "user alarm", then the `alarmCode` will be zeroed out. 
This fixes the `alarmCode` so that it is populated correctly.

### CODE REVIEW

**Comment by ted-miller** [comment]
Awaiting test results from the person who reported the problem.

**Review by EricMarcil — APPROVED** [review]

**Comment by AGregg** [comment]
Just to record what we did to test.  We had been triggering the shock sensor on a robot while monitoring the robot status ros topic.  Before installing this update on the robot controller, the alarm code would not populate in the error_code field of the topic message, but after installing the updated driver the alarm code came through.

PXL_20210901_185549419~2

**Review by AGregg — APPROVED** [review]

**Review by gavanderhoorn — APPROVED** [review]
No regressions from my testing (YRC1000).

**Comment by gavanderhoorn** [comment]
@ted-miller: if we merge #417, could you build `1.9.7`?

**Pull request merged**
