### PR TITLE
Simple io support

### PR DESCRIPTION
**Pull request by shaun-edwards**
#93 re-targeted for `jade-devel` branch.  See #93 for previous discussion.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
You want these changes _just_ in Jade, or also in Jade?

**Comment by shaun-edwards** [comment]
Sorry for the delayed reply.  Because these are "significant" changes, I would like to target them for a new release.

**Comment by gavanderhoorn** [comment]
I'm fine with getting this in Jade only, but just wanted to mention that all included changes are orthogonal to the currently existing functionality.

**Comment by shaun-edwards** [comment]
@gavanderhoorn, I've decided to merge everything into indigo and then I will sync with jade.  Closing this PR as a result.

**Pull request closed without merging**
