### PR TITLE
rebased 266: MA2010 and D500 support

### PR DESCRIPTION
**Pull request by gavanderhoorn**
Rebased version of #266.

I did not want to push commits directly to the `Adamsua-lab/motoman@kinetic-devel`, as I don't know whether that branch is actively being used or not.

Commit provenance is retained.

We'll let CI run, and afterwards I'll squash my fixup commits into the three initial commits by @tdl-ua, so as to not pollute the commit history.

I'm still not sure about the MoveIt configuration (it duplicates files and information from the other packages, among other things), but we'll merge it, as it may help other users.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Thanks again @tdl-ua.

If you're using your `kinetic-devel` right now, pulling from `upstream` here may result in conflicts (as you already have the packages these commits add), but I did not see a way to avoid that without overwriting your `kinetic-devel` (and I did not want to do that).

**Comment by gavanderhoorn** [comment]
Note: I've corrected the `effort` limits in the `motoman_ma2010_support` package you contributed.

@EricMarcil provided me with the correct limits.

**Comment by tdl-ua** [comment]
@gavanderhoorn Thank you for merging and thanks for the considerations. For future consideration, I'm assuming it would be better to not create a PR based on the default branch (e.g., `kinetic-devel`) but to create a dedicated branch for PRs?

**Comment by gavanderhoorn** [comment]
> For future consideration, I'm assuming it would be better to not create a PR based on the default branch (e.g., `kinetic-devel`) but to create a dedicated branch for PRs?

yes, indeed.

that way we don't run the risk of breaking things for you when we push some fixup commits to your PR branch.

**Pull request merged**
