### PR TITLE
MotoROS: Clear motion queue after alarm

### PR DESCRIPTION
**Pull request by ted-miller**
If alarm occurs while queue is full and there is pending data to be processed, then subsequent trajectory commands will fail.

### CODE REVIEW

**Comment by ted-miller** [comment]
Waiting for confirmation from the user that this resolves the issue

**Comment by gavanderhoorn** [comment]
Could you please update the commit comment to include the cause of the issue this is fixing?

It's not clear from the changes why they fix the issue. Having a description of how this change fixes it would be valuable.

**Comment by ted-miller** [comment]
> It's not clear from the changes why they fix the issue

Well... that's probably because it's total nonsense...

As I attempted to write up a description, it made me think about this in more detail. And now I've started second guessing my original assumptions. 

I need to setup some testing.

**Comment by ted-miller** [comment]
My initial message is definitely wrong. But, the commit does fix a problem. I'm going to scrap this PR, make sure the actual issue gets resolved with the user, and then try another PR.

**Pull request closed without merging**
