### PR TITLE
Fix Issue #62

### PR DESCRIPTION
**Pull request by JeremyZoss**
Add motoman_driver dependencies on motoman_msgs, for proper build order.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Looks good.

I have noticed people preferring to add a dependency on the `_gencpp` target (of the specific msg project) if they don't really need any of the other msg generation targets to have run first.

`_EXPORTED_TARGETS` is the documented way though, so +1.

**Comment by JeremyZoss** [comment]
If I understand correctly, `_gencpp` is [deprecated](http://answers.ros.org/question/60994/pkg_name_generate_messages_cpp-vs-pkg_name_gencpp/), but `_generate_messages_cpp` is still a valid alternative.  Since `_EXPORTED_TARGETS` seemed to be [recommended](https://github.com/ros/catkin/issues/547#issuecomment-29740592), that's what I used.

**Comment by gavanderhoorn** [comment]
Yes it is deprecated. See also [C++ message or service dependencies](http://docs.ros.org/indigo/api/catkin/html/howto/format1/cpp_msg_dependencies.html) in the catkin docs.

**Comment by shaun-edwards** [comment]
+1.

**Pull request merged**
